name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM deps
        run: npm ci || npm i

      - name: Add Capacitor deps
        run: |
          npm i @capacitor/core@latest
          npm i -D @capacitor/cli@latest

      - name: Build web
        run: npm run build

      # ایجاد فولدر android و کپی فایل‌های وب داخلش
      - name: Capacitor add/copy (create Android project)
        run: |
          npx cap add android
          npx cap copy

      # حالا که فولدر android و فایل‌های Gradle وجود داره، جاوا و SDK رو ستاپ می‌کنیم
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build APK (debug)
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
